artist-website/config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'admin-login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions


  # This is for the back end homepage
  get 'home/' => 'home#index', as: :home

  # These routes are for shows
  get 'tourdate/' => 'tourdate#index', as: :tourdate

  get 'tourdate/new' => 'tourdate#new', as: :new

  get 'tourdate/:id' => 'tourdate#show', as: :single_tourdate

  post 'tourdate/' => 'tourdate#create', as: :new_tourdate

  get 'tourdate/:id/edit' =>  'tourdate#edit', as: :edit_tourdate

  patch 'tourdate/:id' => 'tourdate#update', as: :update_tourdate

  delete 'tourdate/:id' => 'tourdate#destroy', as: :delete_tourdate


  # These routes are for news posts
  get 'post/' => 'post#index', as: :post

  get 'post/new' => 'post#new', as: :addpost

  get 'post/:id' => 'post#show', as: :single_post

  post 'post/' => 'post#create', as: :new_post

  get 'post/:id/edit' =>  'post#edit', as: :edit_post

  patch 'post/:id' => 'post#update', as: :update_post

  delete 'post/:id' => 'post#destroy', as: :delete_post


  #These routes determine the front end
  root 'application#index'

  get 'about/' => 'application#about', as: :about

  # These two were replaced by the other two routes for News and Shows below
  # get 'news/' => 'application#news'

  # get 'shows/' => 'application#shows'

  get 'music/' => 'application#music', as: :music

  get 'video/' => 'application#video', as: :video

  get 'photos/' => 'application#photos', as: :photos


  #For News and Shows

  get 'news/index' => 'news#index', as: :news

  get 'shows/index' => 'shows#index', as: :shows

end

artist-website/app/models/post.rb
class Post

	include Mongoid::Document

	field :date, type: String
	field :title, type: String
	field :body, type: String
	
end

artist-website/app/models/tourdate.rb
class Tourdate

	include Mongoid::Document

	field :date, type: String
	field :city, type: String
	field :venue, type: String
	field :time, type: String

end

artist-website/app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  field :email, type: String
  field :password_digest, type: String

  has_secure_password

  # attr_accessible :email, :password, :password_confirmation

  validates_uniqueness_of :email
end

artist-website/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_filter :authorize

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end
  helper_method :current_user

  def authorize
  	redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end


end

artist-website/app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

end

artist-website/app/controllers/news_controller.rb
class NewsController < ApplicationController

   def index
   	@post = Post.all
   end
end

artist-website/app/controllers/post_controller.rb
class PostController < ApplicationController

	def index
	    @post = Post.all
	end

	def show
        @post = Post.find(params[:id])
    end

	def new
		@post = Post.new
	end

	def create

		@post = Post.new(post_params)

		if @post.save
			redirect_to post_path
		else
			redirect_to @post, notice: 'There was an error creating the new post.'
		end

	end

	def post_params
	    params.require(:post).permit(:date, :title, :body)
	end

	def edit
      @post = Post.find(params[:id])
    end

    def update
      @post = Post.find(params[:id])
      if @post.update_attributes(params.require(:post).permit(:date, :title, :body))
        redirect_to post_path
      else
        render 'edit'
      end
    end

    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to post_path
    end

end

artist-website/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # skip_before_filter :authorize
  
  def new
  end

  def create
      user = User.where(email: params[:email]).first
      # first make sure we actually find a user
      # then see if user authenticates
      if user && user.authenticate(params[:password])
          # sets the cookie to the browser
          session[:user_id] = user.id
          redirect_to home_path
      else
          flash.now.alert = "Email or password is invalid"
          render "new"
          # redirect_to new_session_path
      end
  end

  def destroy
      # Kill our cookies!
      reset_session
      redirect_to login_path
  end
end

artist-website/app/controllers/shows_controller.rb
class ShowsController < ApplicationController

   def index
   	@tourdate = Tourdate.all
   end
end

artist-website/app/controllers/tourdate_controller.rb
class TourdateController < ApplicationController

  def index
  	@tourdate = Tourdate.all
  end

  def show
  @tourdate = Tourdate.find(params[:id])
  end

  def new
  	@tourdate = Tourdate.new
  end

  def create
  	@tourdate = Tourdate.new(tourdate_params)

  	if @tourdate.save
  		redirect_to tourdate_path
  	else
  		redirect_to @tourdate, notice: 'There was an error creating tour dates.'
  	end
  end

  def tourdate_params
  	params.require(:tourdate).permit(:date, :city, :venue, :time)
  end

  def edit
    @tourdate = Tourdate.find(params[:id])
  end

  def update
    @tourdate = Tourdate.find(params[:id])
    if @tourdate.update_attributes(params.require(:tourdate).permit(:date, :city, :venue, :time))
      redirect_to tourdate_path
    else
      render 'edit'
    end
  end

  def destroy
    @tourdate = Tourdate.find(params[:id])
    @tourdate.destroy
    redirect_to tourdate_path
  end

end

artist-website/app/controllers/users_controller.rb
class UsersController < ApplicationController

    # skip_before_filter :authorize
    
    def index
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
        session[:user_id] = @user.id
            redirect_to home_path, notice: "Thank you for signing up!"
        else
            render "new"
        end
    end

    private
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

artist-website/app/helpers/application_helper.rb
module ApplicationHelper
end

artist-website/app/helpers/sessions_helper.rb
module SessionsHelper
end

artist-website/app/helpers/users_helper.rb
module UsersHelper
end

artist-website/app/views/application/about.html.erb
<!DOCTYPE html>
<head>
	<title>Project 2</title>
	<link rel="stylesheet" style="text/css" href="../../assets/stylesheets/style.css" >
</head>
<body>
	<div class="wrapper">
		<div class="header">
			<%= link_to(root_path) do %>
			  <div class="logo">
			  </div>
		    <% end %>
			<div class="nav-social">
				<div class="social-icons">
				</div>
				<div class="navigation">
					<ul>
						<li><a href="about">About</a></li>
						<li><%= link_to "News", news_path %></li>
						<li><%= link_to "Shows", shows_path %></li>
						<li><a href="music">Music</a></li>
						<li><a href="video">Video</a></li>
						<li><a href="photos">Photos</a></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="content">
				<h1>About This Awesome Rock Band</h1>
				<p>This is a super awesome rock band that has been traveling the world for several years, rocking the socks off of every audience who has ever seen them play.  They have amazing musicianship, super catchy songs, and amazingly energetic stage antics.  They're definitely a must-see band.</p>
			</div>
		</div>
	</div>
</body>
</html>

artist-website/app/views/application/index.html.erb
<!DOCTYPE html>
<head>
	<title>Project 2</title>
	<link rel="stylesheet" style="text/css" href="../../assets/stylesheets/style.css" >
</head>
<body>
	<div class="wrapper">
		<div class="header">
			<%= link_to(root_path) do %>
			  <div class="logo">
			  </div>
		    <% end %>
			<div class="nav-social">
				<div class="social-icons">
				</div>
				<div class="navigation">
					<ul>
						<li><a href="about">About</a></li>
						<li><%= link_to "News", news_path %></li>
						<li><%= link_to "Shows", shows_path %></li>
						<li><a href="music">Music</a></li>
						<li><a href="video">Video</a></li>
						<li><a href="photos">Photos</a></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="content">
			</div>
		</div>
	</div>
</body>
</html>

artist-website/app/views/application/music.html.erb
<!DOCTYPE html>
<head>
	<title>Project 2</title>
	<link rel="stylesheet" style="text/css" href="../../assets/stylesheets/style.css" >
</head>
<body>
	<div class="wrapper">
		<div class="header">
			<%= link_to(root_path) do %>
			  <div class="logo">
			  </div>
		    <% end %>
			<div class="nav-social">
				<div class="social-icons">
				</div>
				<div class="navigation">
					<ul>
						<li><a href="about">About</a></li>
						<li><%= link_to "News", news_path %></li>
						<li><%= link_to "Shows", shows_path %></li>
						<li><a href="music">Music</a></li>
						<li><a href="video">Video</a></li>
						<li><a href="photos">Photos</a></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="content">
			</div>
		</div>
	</div>
</body>
</html>

artist-website/app/views/application/news.html.erb
<!DOCTYPE html>
<head>
	<title>Project 2</title>
	<link rel="stylesheet" style="text/css" href="../../assets/stylesheets/style.css" >
</head>
<body>
	<div class="wrapper">
		<div class="header">
			<%= link_to(root_path) do %>
			  <div class="logo">
			  </div>
		    <% end %>
			<div class="nav-social">
				<div class="social-icons">
				</div>
				<div class="navigation">
					<ul>
						<li><a href="../../views/application/about.html.erb">About</a></li>
						<li><%= link_to "News", news_path %></li>
						<li><%= link_to "Shows", shows_path %></li>
						<li><a href="../../views/application/music.html.erb">Music</a></li>
						<li><a href="../../views/application/video.html.erb">Video</a></li>
						<li><a href="../../views/application/photos.html.erb">Photos</a></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="content">

			</div>
		</div>
	</div>
</body>
</html>

artist-website/app/views/application/photos.html.erb
<!DOCTYPE html>
<head>
	<title>Project 2</title>
	<link rel="stylesheet" style="text/css" href="../../assets/stylesheets/style.css" >
</head>
<body>
	<div class="wrapper">
		<div class="header">
			<%= link_to(root_path) do %>
			  <div class="logo">
			  </div>
		    <% end %>
			<div class="nav-social">
				<div class="social-icons">
				</div>
				<div class="navigation">
					<ul>
						<li><a href="about">About</a></li>
						<li><%= link_to "News", news_path %></li>
						<li><%= link_to "Shows", shows_path %></li>
						<li><a href="music">Music</a></li>
						<li><a href="video">Video</a></li>
						<li><a href="photos">Photos</a></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="content">
			</div>
		</div>
	</div>
</body>
</html>

artist-website/app/views/application/shows.html.erb
<!DOCTYPE html>
<head>
	<title>Project 2</title>
	<link rel="stylesheet" style="text/css" href="../../assets/stylesheets/style.css" >
</head>
<body>
	<div class="wrapper">
		<div class="header">
			<%= link_to(root_path) do %>
			  <div class="logo">
			  </div>
		    <% end %>
			<div class="nav-social">
				<div class="social-icons">
				</div>
				<div class="navigation">
					<ul>
						<li><a href="about">About</a></li>
						<li><%= link_to "News", news_path %></li>
						<li><%= link_to "Shows", shows_path %></li>
						<li><a href="music">Music</a></li>
						<li><a href="video">Video</a></li>
						<li><a href="photos">Photos</a></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="content">
			</div>
		</div>
	</div>
</body>
</html>

artist-website/app/views/application/video.html.erb
<!DOCTYPE html>
<head>
	<title>Project 2</title>
	<link rel="stylesheet" style="text/css" href="../../assets/stylesheets/style.css" >
</head>
<body>
	<div class="wrapper">
		<div class="header">
			<%= link_to(root_path) do %>
			  <div class="logo">
			  </div>
		    <% end %>
			<div class="nav-social">
				<div class="social-icons">
				</div>
				<div class="navigation">
					<ul>
						<li><a href="about">About</a></li>
						<li><%= link_to "News", news_path %></li>
						<li><%= link_to "Shows", shows_path %></li>
						<li><a href="music">Music</a></li>
						<li><a href="video">Video</a></li>
						<li><a href="photos">Photos</a></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="content">
			</div>
		</div>
	</div>
</body>
</html>

artist-website/app/views/home/index.html.erb
<%= link_to "Log Out", logout_path %>
<h1>What Do You Want To Update?</h1>

<div class="options">
	<div class="left">
    <p><%= link_to 'Shows', tourdate_path %></p>
  </div>
  <div class="right">
    <p><%= link_to 'Posts', post_path %></p>
  </div>
</div>

artist-website/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArtistWebsite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>






<%= yield %>

</body>
</html>

artist-website/app/views/news/index.html.erb
<!DOCTYPE html>
<head>
	<title>Project 2</title>
	<link rel="stylesheet" style="text/css" href="../../assets/stylesheets/style.css" >
</head>
<body>
	<div class="wrapper">
		<div class="header">
			<%= link_to(root_path) do %>
			  <div class="logo">
			  </div>
		    <% end %>
			<div class="nav-social">
				<div class="social-icons">
				</div>
				<div class="navigation">
					<ul>
						<li><%= link_to "About", about_path %></li>
						<li><%= link_to "News", news_path %></li>
						<li><%= link_to "Shows", shows_path %></li>
						<li><%= link_to "Music", music_path %></li>
						<li><%= link_to "Video", video_path %></li>
						<li><%= link_to "Photos", photos_path %></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="news-content">
				<h1>Latest News</h1>
	            <div class="post-list">

					<%@post.each do |post| %>
                    <div class="news-post">
					<%= post.date %>
					<%= post.title %>
                    <br>
					<%= post.body %>
				    </div>
                    <br><br>
				<% end %>

	         </div>
			</div>
		</div>
	</div>
</body>
</html>

artist-website/app/views/post/edit.html.erb
<%= link_to "Log Out", logout_path %>
<h1>Editing Post</h1>

  <div class="page-contents">
  	<div class="back-button">
      <%= link_to 'Back to Posts', post_path %>
    </div>
    <%= form_for(@post, :url => {:action => :update, :controller => :post} ) do |p| %>
	<div class="field">
	  <%= p.label :date %><br>
	  <%= p.text_field :date, placeholder: 'MM/DD/YY' %>
	</div>
	<div class="field">
	  <%= p.label :title %><br>
	  <%= p.text_field :title %>
	</div>
	<div class="text-area">
	  <%= p.label :content %><br>
	  <%= p.text_area :body, :size =>'90%x20%' %>
	</div>
	<div class="actions">
	  <%= p.submit "Update Post" %>
	</div>
<% end %>
  </div>

artist-website/app/views/post/index.html.erb
<head>
	<link rel="stylesheet" type="text/css" href="../../assets/stylesheets/backend-style.css" >
</head>
<body>
<%= link_to "Log Out", logout_path %>
	<h1>Edit Your Posts</h1>
	<div class="page-contents">
		<div class="new-entry">
	        <%= link_to 'Create New Post', addpost_path %>
	    </div>
	    <div class="nav-button">
	  	    <%= link_to 'Edit Shows', tourdate_path %>
	    </div>
	    <div class="post-list">
			<table>
			<thead>
				<tr>
				<th>Date</th>
				<th>Title</th>
				<th>Content</th>
				</tr>
				</thead>
				<%@post.each do |post| %>
				<tr>
				<td><%= post.date %></td>
				<td><%= post.title.truncate(50) %></td>
				<td><%= post.body.truncate(25) %></td>
				<td><%= link_to 'Show', single_post_path(post) %></td>
			    <td><%= link_to 'Edit', edit_post_path(post) %></td>
			    <td><%= link_to 'Delete', delete_post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
			<% end %>
			</table>
	    </div>
	</div>
</body>

artist-website/app/views/post/new.html.erb
<%= link_to "Log Out", logout_path %>
<h1>Create a New Post</h1>

  <div class="page-contents">
  	<div class="back-button">
      <%= link_to 'Back to Posts', post_path %>
    </div>
    <%= form_for(@post, :url => {:action => :create, :controller => :post} ) do |p| %>
	<div class="field">
	  <%= p.label :date %><br>
	  <%= p.text_field :date, placeholder: 'MM/DD/YY' %>
	</div>
	<div class="field">
	  <%= p.label :title %><br>
	  <%= p.text_field :title %>
	</div>
	<div class="text-area">
	  <%= p.label :content %><br>
	  <%= p.text_area :body, :size =>'90%x20%' %>
	</div>
	<div class="actions">
	  <%= p.submit "Submit Post" %>
	</div>
<% end %>
  </div>

artist-website/app/views/post/show.html.erb
<%= link_to "Log Out", logout_path %>
<h1> <%= @post.title %> </h1>
<div class="page-contents">
  <p><%= @post.date %></p>
  <p><%= @post.body %></p>

  <p><%= link_to "Back to Posts", post_path %></p>
</div>

artist-website/app/views/shows/index.html.erb
<!DOCTYPE html>
<head>
	<title>Project 2</title>
	<link rel="stylesheet" style="text/css" href="../../assets/stylesheets/style.css" >
</head>
<body>
	<div class="wrapper">
		<div class="header">
			<%= link_to(root_path) do %>
			  <div class="logo">
			  </div>
		    <% end %>
			<div class="nav-social">
				<div class="social-icons">
				</div>
				<div class="navigation">
					<ul>
						<li><%= link_to "About", about_path %></li>
						<li><%= link_to "News", news_path %></li>
						<li><%= link_to "Shows", shows_path %></li>
						<li><%= link_to "Music", music_path %></li>
						<li><%= link_to "Video", video_path %></li>
						<li><%= link_to "Photos", photos_path %></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="tour-dates">
				<h1>Shows</h1>
			    <div class="date-list">
				<table>
				<thead>
				  <tr>
				   <th>Date</th>
				   <th>City</th>
				   <th>Venue</th>
				   <th>Time</th>
				  </tr>
				</thead>
				<%@tourdate.each do |tourdate| %>
				   <tr>
				   <td><%= tourdate.date %></td>
				   <td><%= tourdate.city %></td>
				   <td><%= tourdate.venue %></td>
				   <td><%= tourdate.time %></td>
				   </tr>
				<% end %>
				</table>
			    </div>
			</div>
		</div>
	</div>
</body>
</html>

artist-website/app/views/tourdate/edit.html.erb
<%= link_to "Log Out", logout_path %>
<h1>Editing Show</h1>

<div class="page-contents">
  <div class="back-button">
    <%= link_to 'Back to Shows', tourdate_path %>
  </div>
    <%= form_for(@tourdate, :url => {:action => :update, :controller => :tourdate}) do |f| %>
    <div class="field">
      <%= f.label :date %><br>
      <%= f.text_field :date, placeholder: 'DD/MM/YY' %>
    </div>
    <div class="field">
      <%= f.label :city %><br>
      <%= f.text_field :city %>
    </div>
    <div class="field">
      <%= f.label :venue %><br>
      <%= f.text_field :venue %>
    </div>
    <div class="field">
      <%= f.label :time %><br>
      <%= f.text_field :time %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit "Update Show" %>
    </div>
  <% end %>

</div>

artist-website/app/views/tourdate/index.html.erb
<head>
	<link rel="stylesheet" type="text/css" href="../../assets/stylesheets/backend-style.css" >
</head>
<body>
<%= link_to "Log Out", logout_path %>
	<h1>Edit Your Shows</h1>
	<div class="page-contents">
      <div class="new-entry">
	    <%= link_to "Create New Show", new_path %>
	  </div>
	  <div class="nav-button">
	  	<%= link_to 'Edit News Posts', post_path %>
	  </div>

		<div class="date-list">
			<table>
			<thead>
			  <tr>
			   <th>Date</th>
			   <th>City</th>
			   <th>Venue</th>
			   <th>Time</th>
			  </tr>
			</thead>
			<%@tourdate.each do |tourdate| %>
			   <tr>
			   <td><%= tourdate.date %></td>
			   <td><%= tourdate.city %></td>
			   <td><%= tourdate.venue %></td>
			   <td><%= tourdate.time %></td>
			   <td><%= link_to 'Show', single_tourdate_path(tourdate) %></td>
			   <td><%= link_to 'Edit', edit_tourdate_path(tourdate) %></td>
			   <td><%= link_to 'Delete', delete_tourdate_path(tourdate), method: :delete, data: { confirm: 'Are you sure?' } %></td>
			   </tr>
			<% end %>
			</table>
		</div>
	</div>

</body>

artist-website/app/views/tourdate/new.html.erb
<%= link_to "Log Out", logout_path %>
<h1>Create a New Show</h1>

<div class="page-contents">
  <div class="back-button">
    <%= link_to 'Back to Shows', tourdate_path %>
  </div>
    <%= form_for(@tourdate, :url => {:action => :create, :controller => :tourdate}) do |f| %>
    <div class="field">
      <%= f.label :date %><br>
      <%= f.text_field :date, placeholder: 'DD/MM/YY' %>
    </div>
    <div class="field">
      <%= f.label :city %><br>
      <%= f.text_field :city %>
    </div>
    <div class="field">
      <%= f.label :venue %><br>
      <%= f.text_field :venue %>
    </div>
    <div class="field">
      <%= f.label :time %><br>
      <%= f.text_field :time %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit "Create New Show" %>
    </div>
  <% end %>
</div>

artist-website/app/views/tourdate/show.html.erb
<%= link_to "Log Out", logout_path %>
<h1> <%= @tourdate.venue %>, <%= @tourdate.date %> </h1>
<div class="page-contents">
  <p>This show is on <%= @tourdate.date %> in <%= @tourdate.city %> at <%= @tourdate.venue %> and starts at <%= @tourdate.time %>. </p>

  <p><%= link_to "Back to Shows", tourdate_path %></p>
</div>

artist-website/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="login-info">
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>
</div>